/**
 * FIFO VIP Testbench
 * C++ Verilator testbench using UVM-style components
 * Create Date: 2026-04-23
 *
 * Usage:
 *   make
 *   ./obj_dir/Vfifo
 */

#include <iostream>
#include <memory>
#include <random>
#include <cstdlib>
#include <verilated.h>
#include <verilated_vcd_c.h>

// Include the Verilated DUT header (generated by Verilator)
#include "Vfifo.h"

// Include VIP components
#include "fifo_transaction.h"
#include "fifo_driver.h"
#include "fifo_monitor.h"
#include "fifo_scoreboard.h"
#include "fifo_coverage.h"

using namespace fifo_vip;

//=============================================================================
// Configuration
//=============================================================================
struct TestConfig {
    int depth = 12;
    int data_width = 8;
    bool rd_buffer = true;
    bool async = false;  // Use synchronous mode for simplicity
    int num_writes = 20;
    int num_reads = 20;
    bool verbose = false;
    bool enable_waves = true;
    unsigned int seed = 12345;
};

//=============================================================================
// Clock and Reset Generation
//=============================================================================
class ClockReset {
public:
    ClockReset(Vfifo* dut) : dut_(dut), time_(0) {}

    void reset(int cycles = 5) {
        dut_->rst = 1;
        for (int i = 0; i < cycles; i++) {
            tick();
        }
        dut_->rst = 0;
        tick();
    }

    void tick() {
        // Rising edge
        dut_->wr_clk = 1;
        dut_->rd_clk = 1;
        dut_->eval();
        time_ += 5;

        // Falling edge
        dut_->wr_clk = 0;
        dut_->rd_clk = 0;
        dut_->eval();
        time_ += 5;
    }

    uint64_t time() const { return time_; }

private:
    Vfifo* dut_;
    uint64_t time_;
};

//=============================================================================
// Test Sequences
//=============================================================================

/**
 * Simple directed test: Fill FIFO, then drain it
 */
void run_simple_test(Vfifo* dut, ClockReset& clk, FifoScoreboard& sb,
                     FifoCoverage& cov, const TestConfig& cfg) {
    std::cout << "\n=== Running Simple Test ===" << std::endl;

    FifoDriverSync<Vfifo> driver(dut);
    driver.data_width = cfg.data_width;
    driver.rd_buffer = cfg.rd_buffer;
    driver.verbose = cfg.verbose;
    driver.init();

    // Connect driver to scoreboard
    driver.on_write_transaction = [&](const FifoTransaction& t) {
        sb.write_in(t);
        cov.sample(t);
        cov.sample_fill_level(sb.get_model_size());
    };
    driver.on_read_transaction = [&](const FifoTransaction& t) {
        sb.read_in(t);
        cov.sample(t);
        cov.sample_fill_level(sb.get_model_size());
    };

    // Fill FIFO with known values
    std::cout << "Filling FIFO..." << std::endl;
    for (int i = 0; i < cfg.depth; i++) {
        uint64_t data = (i * 0x11) & ((1 << cfg.data_width) - 1);
        driver.write(data);
    }

    // Try to write when full (should fail)
    std::cout << "Attempting write when full..." << std::endl;
    driver.write(0xFF);

    // Read all values back
    std::cout << "Draining FIFO..." << std::endl;
    for (int i = 0; i < cfg.depth; i++) {
        driver.read();
    }

    // Try to read when empty (should fail)
    std::cout << "Attempting read when empty..." << std::endl;
    driver.read();

    std::cout << "Simple test complete." << std::endl;
}

/**
 * Random test: Mixed random reads and writes
 */
void run_random_test(Vfifo* dut, ClockReset& clk, FifoScoreboard& sb,
                     FifoCoverage& cov, const TestConfig& cfg) {
    std::cout << "\n=== Running Random Test ===" << std::endl;

    std::mt19937 rng(cfg.seed);

    FifoDriverSync<Vfifo> driver(dut);
    driver.data_width = cfg.data_width;
    driver.rd_buffer = cfg.rd_buffer;
    driver.verbose = cfg.verbose;
    driver.init();

    // Connect driver to scoreboard
    driver.on_write_transaction = [&](const FifoTransaction& t) {
        sb.write_in(t);
        cov.sample(t);
        cov.sample_fill_level(sb.get_model_size());
    };
    driver.on_read_transaction = [&](const FifoTransaction& t) {
        sb.read_in(t);
        cov.sample(t);
        cov.sample_fill_level(sb.get_model_size());
    };

    // Phase 1: Write more than read to fill up
    std::cout << "Phase 1: Filling..." << std::endl;
    for (int i = 0; i < cfg.num_writes; i++) {
        FifoTransaction t;
        t.set_data_width(cfg.data_width);
        t.randomize_with_op(FifoOp::WRITE, rng);
        driver.write(t.data);

        // Occasionally read
        if (i % 3 == 0 && !sb.is_model_empty()) {
            driver.read();
        }
    }

    // Phase 2: Read more than write to drain
    std::cout << "Phase 2: Draining..." << std::endl;
    for (int i = 0; i < cfg.num_reads; i++) {
        if (!sb.is_model_empty()) {
            driver.read();
        }

        // Occasionally write
        if (i % 4 == 0 && !sb.is_model_full()) {
            FifoTransaction t;
            t.set_data_width(cfg.data_width);
            t.randomize_with_op(FifoOp::WRITE, rng);
            driver.write(t.data);
        }
    }

    // Drain remaining
    std::cout << "Draining remaining entries..." << std::endl;
    while (!sb.is_model_empty()) {
        driver.read();
    }

    std::cout << "Random test complete." << std::endl;
}

/**
 * Stress test: Back-to-back operations
 */
void run_stress_test(Vfifo* dut, ClockReset& clk, FifoScoreboard& sb,
                     FifoCoverage& cov, const TestConfig& cfg) {
    std::cout << "\n=== Running Stress Test ===" << std::endl;

    std::mt19937 rng(cfg.seed + 1);

    FifoDriverSync<Vfifo> driver(dut);
    driver.data_width = cfg.data_width;
    driver.rd_buffer = cfg.rd_buffer;
    driver.verbose = cfg.verbose;
    driver.init();

    // Connect driver to scoreboard
    driver.on_write_transaction = [&](const FifoTransaction& t) {
        sb.write_in(t);
        cov.sample(t);
        cov.sample_fill_level(sb.get_model_size());
    };
    driver.on_read_transaction = [&](const FifoTransaction& t) {
        sb.read_in(t);
        cov.sample(t);
        cov.sample_fill_level(sb.get_model_size());
    };

    // Rapid fill/drain cycles
    for (int cycle = 0; cycle < 5; cycle++) {
        std::cout << "Stress cycle " << cycle + 1 << "/5" << std::endl;

        // Fill completely
        while (!sb.is_model_full()) {
            FifoTransaction t;
            t.set_data_width(cfg.data_width);
            t.randomize_with_op(FifoOp::WRITE, rng);
            driver.write(t.data);
        }

        // Drain completely
        while (!sb.is_model_empty()) {
            driver.read();
        }
    }

    std::cout << "Stress test complete." << std::endl;
}

//=============================================================================
// Main
//=============================================================================
int main(int argc, char** argv) {
    // Initialize Verilator
    Verilated::commandArgs(argc, argv);

    // Parse command line arguments
    TestConfig cfg;
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "-v" || arg == "--verbose") {
            cfg.verbose = true;
        } else if (arg == "--no-waves") {
            cfg.enable_waves = false;
        } else if (arg.substr(0, 7) == "--seed=") {
            cfg.seed = std::stoul(arg.substr(7));
        } else if (arg.substr(0, 9) == "--writes=") {
            cfg.num_writes = std::stoi(arg.substr(9));
        } else if (arg.substr(0, 8) == "--reads=") {
            cfg.num_reads = std::stoi(arg.substr(8));
        }
    }

    std::cout << "==================================================" << std::endl;
    std::cout << "FIFO VIP C++ Verilator Testbench" << std::endl;
    std::cout << "==================================================" << std::endl;
    std::cout << "Configuration:" << std::endl;
    std::cout << "  Depth:      " << cfg.depth << std::endl;
    std::cout << "  Data Width: " << cfg.data_width << std::endl;
    std::cout << "  RD Buffer:  " << (cfg.rd_buffer ? "Yes" : "No") << std::endl;
    std::cout << "  Seed:       " << cfg.seed << std::endl;
    std::cout << "  Verbose:    " << (cfg.verbose ? "Yes" : "No") << std::endl;
    std::cout << "==================================================" << std::endl;

    // Create DUT instance
    auto dut = std::make_unique<Vfifo>();

    // Create VCD trace
    VerilatedVcdC* tfp = nullptr;
    if (cfg.enable_waves) {
        Verilated::traceEverOn(true);
        tfp = new VerilatedVcdC;
        dut->trace(tfp, 99);
        tfp->open("fifo_tb.vcd");
    }

    // Create clock/reset controller
    ClockReset clk(dut.get());

    // Create VIP components
    FifoScoreboard scoreboard;
    scoreboard.depth = cfg.depth;
    scoreboard.data_width = cfg.data_width;
    scoreboard.verbose = cfg.verbose;

    FifoCoverage coverage;
    coverage.depth = cfg.depth;
    coverage.data_width = cfg.data_width;

    // Initialize signals
    dut->wr_clk = 0;
    dut->rd_clk = 0;
    dut->rst = 0;
    dut->wr_en = 0;
    dut->rd_en = 0;
    dut->data_wr = 0;
    dut->eval();

    // Reset sequence
    std::cout << "\nApplying reset..." << std::endl;
    clk.reset(10);

    // Run tests
    run_simple_test(dut.get(), clk, scoreboard, coverage, cfg);
    run_random_test(dut.get(), clk, scoreboard, coverage, cfg);
    run_stress_test(dut.get(), clk, scoreboard, coverage, cfg);

    // Final reports
    scoreboard.report();
    coverage.report();

    // Cleanup
    if (tfp) {
        tfp->close();
        delete tfp;
    }

    // Return exit code
    return scoreboard.passed() ? 0 : 1;
}
